-- Initial schema for the Omie ETL pipeline.
-- Apply through the Supabase CLI after reviewing in the target project.

create table if not exists public.pipeline_runs (
    run_id text primary key,
    resource text not null check (resource in ('customers', 'services')),
    account_id text,
    mode text not null check (mode in ('full', 'incremental', 'replay')),
    status text not null check (status in ('running', 'success', 'partial', 'failed')),
    started_at timestamptz not null,
    finished_at timestamptz,
    page_count integer not null default 0 check (page_count >= 0),
    record_count integer not null default 0 check (record_count >= 0),
    error text,
    created_at timestamptz not null default now()
);

create table if not exists public.pipeline_rejections (
    id bigint generated by default as identity primary key,
    run_id text not null references public.pipeline_runs(run_id),
    resource text not null check (resource in ('customers', 'services')),
    reason text not null,
    source_payload jsonb not null,
    created_at timestamptz not null default now()
);

create index if not exists pipeline_rejections_run_id_idx
    on public.pipeline_rejections (run_id);

create table if not exists public.pipeline_checkpoints (
    resource text primary key check (resource in ('customers', 'services', 'receivables', 'categories')),
    checkpoint text not null,
    updated_at timestamptz not null default now()
);

create table if not exists public.omie_customers (
    external_id text primary key,
    customer_id bigint not null,
    integration_code text,
    legal_name text,
    trade_name text,
    tax_id text,
    person_type text not null check (person_type in ('individual', 'company')),
    state_registration text,
    municipal_registration text,
    cnae text,
    city text,
    state text,
    city_ibge text,
    country_code text,
    postal_code text,
    address text,
    address_number text,
    address_complement text,
    neighborhood text,
    emails text[] not null default '{}',
    phone_1 text,
    phone_2 text,
    active boolean not null default true,
    is_abroad boolean not null default false,
    is_simple_national boolean not null default false,
    billing_blocked boolean not null default false,
    generates_billing boolean not null default false,
    tags text[] not null default '{}',
    imported_by_api boolean not null default false,
    created_at date,
    updated_at date,
    source_payload jsonb not null,
    loaded_at timestamptz not null default now()
);

create index if not exists omie_customers_state_idx
    on public.omie_customers (state);
create index if not exists omie_customers_active_idx
    on public.omie_customers (active) where active = true;
create index if not exists omie_customers_tax_id_idx
    on public.omie_customers (tax_id);

create table if not exists public.omie_services (
    external_id text primary key,
    service_id bigint not null,
    integration_code text,
    service_code text,
    name text,
    description text,
    category_code text,
    municipal_service_code text,
    lc116_code text,
    taxation_code text,
    nbs_code text,
    unit_price numeric(18, 4),
    discount_value numeric(18, 4),
    discount_rate numeric(12, 4),
    iss_rate numeric(12, 4),
    pis_rate numeric(12, 4),
    cofins_rate numeric(12, 4),
    csll_rate numeric(12, 4),
    ir_rate numeric(12, 4),
    inss_rate numeric(12, 4),
    iss_withheld text,
    pis_withheld text,
    cofins_withheld text,
    inss_withheld text,
    active boolean not null default true,
    imported_by_api boolean not null default false,
    created_at date,
    updated_at date,
    source_payload jsonb not null,
    loaded_at timestamptz not null default now()
);

create index if not exists omie_services_active_idx
    on public.omie_services (active) where active = true;
create index if not exists omie_services_category_idx
    on public.omie_services (category_code);
create index if not exists omie_services_code_idx
    on public.omie_services (service_code);

alter table public.pipeline_runs enable row level security;
alter table public.pipeline_rejections enable row level security;
alter table public.pipeline_checkpoints enable row level security;
alter table public.omie_customers enable row level security;
alter table public.omie_services enable row level security;

revoke all on table public.pipeline_runs from anon, authenticated;
revoke all on table public.pipeline_rejections from anon, authenticated;
revoke all on table public.pipeline_checkpoints from anon, authenticated;
revoke all on table public.omie_customers from anon, authenticated;
revoke all on table public.omie_services from anon, authenticated;
